name: Build
on:
  pull_request:
  push:
    branches:
      - main
      - develop
      - hotfix/*

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
      - name: Get the sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Execute test.ps1
        shell: pwsh
        run: ./test.ps1
