name: Obtain
on:
  pull_request:
  push:
    branches:
      - main
      - develop
      - hotfix/*

jobs:
  build:
    name: Build (${{ matrix.os }}, dotnet8=${{ matrix.install-dotnet8 }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        install-dotnet8: [true, false]
    steps:
      - name: Get the sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Execute test.ps1
        shell: pwsh
        run: |
          if ("${{ matrix.install-dotnet8 }}" -eq "true") {
            ./test.ps1 -InstallDotNet8
          } else {
            ./test.ps1
          }
